kind: pipeline
type: docker
name: test

platform:
  arch: arm64

steps:
  - name: run-tests
    image: maven:3.9.5
    commands:
      - mvn test
  - name: code-analysis
    image: spookyless/sonarqube-scanner
    failure: ignore
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
      sonar_key:
        from_secret: sonar_key
      sonar_name:
        from_secret: sonar_name
      binaries: "./target/classes"
      java_coverage_plugin: "jacoco"
      surefire_reportsPath: "./target/surefire-reports"
      java_test: "./target/test-classes"
      exclusions: "src/test/**/*"
